name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]   # main 브랜치에 push할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # QEMU (다른 아키텍처 빌드 지원)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx (멀티 플랫폼 빌드 도구)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image (multi-arch)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64   # 멀티 아키텍처 빌드
          tags: zero624dev/zerobot:latest